package: url
version: '1.0.0-beta4'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:url'
    perm: admin[]
    pjax: false
    icon: rex-icon fa fa-anchor
    subpages:
        generate:
            title: 'translate:generate'

requires:
    redaxo: '^5.0'

#load: late
